# Generated by Django 5.0.2 on 2024-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_match',
            name='match',
        ),
        migrations.AlterField(
            model_name='match',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='catchphrase',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='match_history',
        ),
        migrations.DeleteModel(
            name='scheduled_match',
        ),
    ]
