# Generated by Django 5.0.2 on 2024-05-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='looser',
            new_name='loser',
        ),
        migrations.AddField(
            model_name='accounts',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='request_accounts', to='api.accounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='spectate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournament_matches', to='api.match'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_accounts', to='api.accounts'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='challengeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_organizer', to='api.accounts'),
        ),
    ]
