# Generated by Django 5.0.2 on 2024-03-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_scheduled_match_match_alter_match_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='catchphrase',
        ),
        migrations.DeleteModel(
            name='match',
        ),
        migrations.DeleteModel(
            name='tournament',
        ),
    ]
