# Generated by Django 5.0.2 on 2024-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_looser_match_loser_accounts_friend_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.AddField(
            model_name='tournament',
            name='allContenders',
            field=models.ManyToManyField(blank=True, to='api.accounts'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='background',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tournament',
            name='history',
            field=models.ManyToManyField(blank=True, to='api.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='maxContenders',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizerName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reasonForNoWinner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winnerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winnerName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(default='pong', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.CharField(default='default_tournament_picture.jpeg', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='sample_tournament', max_length=30),
        ),
    ]
