# Generated by Django 5.0.2 on 2024-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_match_tournament_remove_tournament_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='background',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
