# Generated by Django 5.0.2 on 2024-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tournament_background_alter_tournament_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='background',
            field=models.ImageField(upload_to='staticfiles'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(upload_to='staticfiles'),
        ),
    ]
