# Generated by Django 5.0.2 on 2024-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tournament_background_alter_tournament_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='background',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
