# Generated by Django 5.0.2 on 2024-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tournament_background_alter_tournament_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='background',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
