# Generated by Django 5.0.2 on 2024-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tournament_background_alter_tournament_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpeg', upload_to=''),
        ),
    ]
