# Generated by Django 5.0.2 on 2024-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_accounts_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpeg', upload_to=''),
        ),
    ]
