# Generated by Django 5.0.2 on 2024-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_accounts_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_stats',
            name='rank',
            field=models.ImageField(default="pirate-symbol-mark-svgrepo-com.svg'", upload_to=''),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='rank',
            field=models.ImageField(default="pirate-symbol-mark-svgrepo-com.svg'", upload_to=''),
        ),
    ]
