# Generated by Django 5.0.2 on 2024-05-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chess_stats_rank_alter_pong_stats_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_stats',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
