# Generated by Django 5.0.2 on 2024-05-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_chess_stats_rank_alter_pong_stats_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='chess_stats',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='pong_stats',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='tournaments',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='chess_stats',
            name='challenged',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='allContenders',
        ),
        migrations.RemoveField(
            model_name='chess_stats',
            name='challengers',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='history',
        ),
        migrations.DeleteModel(
            name='Pong_stats',
        ),
    ]
