# Generated by Django 5.0.2 on 2024-05-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_accounts_blocked_remove_accounts_chess_stats_and_more'),
        ('game', '0005_alter_room_player1_alter_room_player2_match'),
        ('tournaments', '0006_tournament_delete_specifictournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Chess_stats',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
