version: '3'
name: "transcendence"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: transcendence #${POSTGRES_USER}
      POSTGRES_PASSWORD: pass #${POSTGRES_PASSWORD}
      POSTGRES_DB: db #${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: requirements/Dockerfile_django
    container_name: django
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - db
      - redis
    restart: unless-stopped

  node:
    image: "node:14"
    user: "node"
    depends_on:
      - nginx 
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    container_name: node
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: requirements/Dockerfile_nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis 
    ports:
      - "6379:6379"

