version: '3'
name: "transcendence"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: transcendence #${POSTGRES_USER}
      POSTGRES_PASSWORD: pass #${POSTGRES_PASSWORD}
      POSTGRES_DB: db #${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: requirements/Dockerfile_django
    command: sh /django_launch.sh
    container_name: django
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - db
    restart: unless-stopped

  node:
    build:
      context: .
      dockerfile: requirements/Dockerfile_node
    container_name: node
    # command: /bin /node_launch.sh
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: requirements/Dockerfile_nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped

