version: '3'
name: "transcendence"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: transcendence #${POSTGRES_USER}
      POSTGRES_PASSWORD: pass #${POSTGRES_PASSWORD}
      POSTGRES_DB: db #${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: django
    command: sh django_launch.sh
    ports:
      - '8000:8000'
    volumes:
      - ./transcendence:/usr/src/app/transcendence
    depends_on:
      - db
    restart: unless-stopped

# nginx:
#   build: requirements/nginx
#   image: nginx
#   ports:
#     - "443:443"
#   networks:
#     - inception
#   volumes:
#     - wordpress_data:/var/www/wordpress
#   depends_on:
#     - wordpress
#   restart: unless-stopped

