version: '3'

# django_data:
#   driver: local
#   driver_opts:
#     type: none
#     device: #TODO
#     o: bind
#
#networks:
#  transcendence:

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: transcendence #${POSTGRES_USER}
      POSTGRES_PASSWORD: pass #${POSTGRES_PASSWORD}
      POSTGRES_DB: db #${POSTGRES_DB}
#    network:
#      - transcendence
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

# django:
#   image: django
#   networks:
#     - transcendence
#   volumes:
#     - django_data:./transcendence
#   depends_on:
#     - postgres
#   restart: unless-stopped
#
# nginx:
#   build: requirements/nginx
#   image: nginx
#   ports:
#     - "443:443"
#   networks:
#     - inception
#   volumes:
#     - wordpress_data:/var/www/wordpress
#   depends_on:
#     - wordpress
#   restart: unless-stopped

