version: '3'

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cycollar/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cycollar/data/wordpress_data
      o: bind

networks:
  inception:

services:
  db:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    network:
      - transcendence
    volumes:
      - postgres_data:/var/lib/
    restart: unless-stopped

  django:
    build: requirements/wordpress
    image: wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    environment:
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DB=${MARIADB_DB}
    restart: unless-stopped

  nginx:
    build: requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: unless-stopped

