version: '3'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: #TODO
      o: bind
  django_data:
    driver: local
    driver_opts:
      type: none
      device: #TODO
      o: bind

networks:
  transcendence:

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "transcendance"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: postgres
    network:
      - transcendence
    volumes:
      - postgres_data:./postgres
    restart: unless-stopped

  django:
    build: #TODO
    image: django
    networks:
      - transcendence
    volumes:
      - django_data:./transcendence
    depends_on:
      - postgres
    restart: unless-stopped

# nginx:
#   build: requirements/nginx
#   image: nginx
#   ports:
#     - "443:443"
#   networks:
#     - inception
#   volumes:
#     - wordpress_data:/var/www/wordpress
#   depends_on:
#     - wordpress
#   restart: unless-stopped

