"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nykvpo$=j_ny&%$pe7a#ktm!oaq7)1+os#u@pv6u)&b920jt83'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = []

# AUTH_USER_MODEL = "api.User"
AUTHENTICATION_BACKENDS = ('authenticate.backends.MyBackend',)
# Application definition

INSTALLED_APPS = [
    'daphne',
    'api',
    'game',
    'authenticate',
    'tournaments',
    'stockfish',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db',
        'USER': 'transcendence',
        'PASSWORD': 'pass',
        'HOST': 'db',
        'PORT': '5432'
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
#AUTH_USER_MODEL = 'django.contrib.auth.models.User'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = '/backend/backend/'
STATIC_URL = '/static/'

STORAGES = {
    "default" : {
        "BACKEND": "django.core.files.storage.FileSystemStorage"
    },
    "staticfiles" : {
        "BACKEND" : 'django.contrib.staticfiles.storage.StaticFilesStorage'
    },
    # "images" : {
    #     "BACKEND" : 'django.contrib.staticfiles.storage.StaticFilesStorage',
    #     "OPTIONS" : {
    #         "location" : "/images",
    #     }
    # }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'applogfile': {
            'level':'DEBUG',
            'class' : 'logging.FileHandler',
            'filename' : 'debug.log'
        },
        'console' : {
            'level' : 'DEBUG',
            'class' : 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['applogfile'],
            'level': 'DEBUG'
        },
        'api.consumers' : {
            'handlers' : ['console', 'applogfile'],
            'level' : 'DEBUG'
        },
        'game.views' : {
            'handlers' : ['console', 'applogfile'],
            'level' : 'DEBUG'
        },
        'tournaments.views' : {
            'handlers' : ['console', 'applogfile'],
            'level' : 'DEBUG'
        },
        'api.consumers' : {
            'handlers' : ['console', 'applogfile'],
            'level' : 'DEBUG'
        }
    }
}