# Generated by Django 5.0.2 on 2024-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sample_tournament', max_length=30)),
                ('game', models.CharField(default='pong', max_length=100)),
                ('picture', models.ImageField(blank=True, default=None, upload_to='')),
                ('background', models.ImageField(blank=True, default=None, upload_to='')),
                ('maxContenders', models.IntegerField(default=4)),
                ('description', models.CharField(default='', max_length=1000)),
                ('reasonForNoWinner', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
