# Generated by Django 5.0.2 on 2024-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_match_game_room_cancelled_room_player1ready_and_more'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='history',
            field=models.ManyToManyField(blank=True, to='game.match'),
        ),
    ]
