# Generated by Django 5.0.2 on 2024-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='selfContender',
        ),
        migrations.AddField(
            model_name='tournament',
            name='contenders',
            field=models.ManyToManyField(blank=True, to='tournaments.tournament'),
        ),
    ]
