# Generated by Django 5.0.2 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_player1_match_player2_room_player1_and_more'),
        ('tournaments', '0002_tournament_allcontenders_tournament_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='history',
            field=models.ManyToManyField(blank=True, to='game.match'),
        ),
    ]
