# Generated by Django 5.0.2 on 2024-05-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_selfcontender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='SpecificTournament',
        ),
    ]
