# Generated by Django 5.0.2 on 2024-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_matchtournament_room_match'),
        ('tournaments', '0003_tournament_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nextMatches',
            field=models.ManyToManyField(blank=True, to='game.room'),
        ),
    ]
