# Generated by Django 5.0.2 on 2024-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_looser_match_loser_accounts_friend_requests_and_more'),
        ('tournaments', '0004_rename_contenders_specifictournament_allcontenders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifictournament',
            name='allContenders',
            field=models.ManyToManyField(blank=True, to='api.accounts'),
        ),
        migrations.AlterField(
            model_name='specifictournament',
            name='history',
            field=models.ManyToManyField(blank=True, to='api.match'),
        ),
    ]
