# Generated by Django 5.0.2 on 2024-03-19 11:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=255)),
                ('moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('turn', models.BooleanField(verbose_name=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.ball')),
                ('paddle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.paddle')),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.score')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mmr', models.IntegerField()),
                ('victories', models.PositiveIntegerField(default=0)),
                ('defeats', models.PositiveIntegerField(default=0)),
                ('friend_list', models.ManyToManyField(related_name='friends', to='game.player')),
                ('friend_request_list', models.ManyToManyField(related_name='friend_requests', to='game.player')),
                ('waiting_challenges_list', models.ManyToManyField(related_name='waiting_challenges', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
                ('players', models.ManyToManyField(to='game.player')),
            ],
        ),
    ]
