# Generated by Django 5.0.2 on 2024-04-05 09:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P1', models.IntegerField(default=1)),
                ('P2', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P1', models.IntegerField(default=0)),
                ('P2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -0 1', max_length=255)),
                ('moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('turn', models.BooleanField(default=True, verbose_name=True)),
                ('kingpin', models.BooleanField(default=False, verbose_name=True)),
                ('checkmate', models.BooleanField(default=False, verbose_name=True)),
                ('promotion', models.CharField(max_length=10, null=True)),
                ('ball', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.ball')),
                ('paddle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.paddle')),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.score')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pong', max_length=100)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='api.accounts')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='api.accounts')),
            ],
        ),
    ]
