# Generated by Django 5.0.2 on 2024-06-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchTournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchTournament', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_a', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_b', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='paddle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.paddle'),
        ),
        migrations.AddField(
            model_name='room',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='game.match'),
        ),
        migrations.AddField(
            model_name='room',
            name='nextRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_room', to='game.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomTournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomTournament', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.score'),
        ),
    ]
