# Generated by Django 5.0.2 on 2024-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='spectate',
            field=models.BooleanField(default=True),
        ),
    ]
