# Generated by Django 5.0.2 on 2024-05-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_spectate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2',
        ),
    ]
