# Generated by Django 5.0.2 on 2024-03-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
