# Generated by Django 5.0.2 on 2024-06-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_player1_match_player2_room_player1_and_more'),
        ('tournaments', '0003_tournament_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchTournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchTournament', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='room',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='game.match'),
        ),
    ]
