# Generated by Django 5.0.2 on 2024-06-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_matchtournament_room_match'),
        ('tournaments', '0004_tournament_nextmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomTournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomTournament', to='tournaments.tournament'),
        ),
    ]
