# Generated by Django 5.0.2 on 2024-03-19 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_room_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='ball',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='pong', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='moves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='turn',
            field=models.BooleanField(default=True, verbose_name=True),
        ),
        migrations.AlterField(
            model_name='paddle',
            name='P1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paddle',
            name='P2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='mmr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='guest', max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='P1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='P2',
            field=models.IntegerField(default=0),
        ),
    ]
