# Generated by Django 5.0.2 on 2024-05-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_chess_stats_rank_alter_pong_stats_rank'),
        ('game', '0003_remove_room_player1_remove_room_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='api.accounts'),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='api.accounts'),
        ),
    ]
