# Generated by Django 5.0.2 on 2024-03-19 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_ball_angle_alter_ball_speed_alter_ball_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='moves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
