# Generated by Django 5.0.2 on 2024-06-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_roomtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nextRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_room', to='game.room'),
        ),
    ]
