# Generated by Django 5.0.2 on 2024-05-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_room_player1_alter_room_player2_match'),
        ('profiles', '0009_alter_chess_stats_challenged_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='loser',
            new_name='player2',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_a', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
