# Generated by Django 5.0.2 on 2024-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_nextroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.CharField(default=''),
        ),
    ]
