# Generated by Django 5.0.2 on 2024-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_loser_match_player2_match_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1Ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player2Ready',
            field=models.BooleanField(default=False),
        ),
    ]
