# Generated by Django 5.0.2 on 2024-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_room_player1ready_room_player2ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game',
        ),
        migrations.AddField(
            model_name='room',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player1Replay',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2Replay',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
