# Generated by Django 5.0.2 on 2024-06-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_match_game_room_cancelled_room_player1replay_and_more'),
        ('profiles', '0021_remove_profile_matches_chess_stats_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='profiles.profile'),
        ),
    ]
