# Generated by Django 5.0.2 on 2024-06-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_room_player1_alter_room_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.match'),
        ),
    ]
