# Generated by Django 5.0.2 on 2024-06-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_room_match'),
        ('tournaments', '0006_tournament_delete_specifictournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament'),
        ),
    ]
