export function getLanguages() {
    return {en : English(), fr : French(), de : Deutsch()}
}

function English() {
    return {
        menu1 : 'Login',
        menu2 : 'Logout',
        menu3 : 'Settings',
        menu4 : 'Profile',
        menu5 : 'Play',
        menu6 : 'Leaderboard',
        menu7 : 'Tournaments',
        menu8 : 'About',
        aboutTitle : 'About this project',
        about1 : 'This is ft_transcendence, the final project of 19\'s common core.',
        about2 : 'The goal is to make a Single Page Application (SPA) designed to let players confront each other in Pong !',
        about3 : 'Some modules were added to that basis :',
        module1 : 'Bootstrap and React were used to make the frontend',
        module2 : 'Django was used to make the backend',
        module3 : 'The games are handled by the server (API) (Except for local matches)',
        module4 : 'The website is linked to a database, so we don\'t lose anything when we shut it down (except for the chat, which is session dependant)',
        module5 : 'Another game is available (Chess)',
        module6 : 'The chat',
        module7 : 'You may play against a remote player, you don\'t HAVE to share a keyboard',
        module8 : 'You may visit the website on (nearly) any browser',
        module9 : 'You may visit the website on any screen size',
        module10 : 'You may create an account, manage your profile, add people as friends and some other social features',
        module11 : 'The website is available in English, French and Deutsch',
        about4 : 'The team is composed of :',
        question1 : 'What\'s the difference between muted and blocked users ?',
        answer1_1 : 'Mute will only prevent a specific user\'s messages to be displayed in your chat. It is session dependant, meaning if you logout / login or reload the page, all muted users will be displayed again.',
        answer1_2 : 'Blocking a user also shuts him down in the chat but not only. He will leave your friendlist if he was in it and won\'t be allowed to send you another friend request or challenge you. And he will stay blocked over a logout / login or reaload on your part.',
        question2 : 'Why can\'t I challenge some of my friends ?',
        answer2 : 'They probably unchecked the \'Challengeable\' option in their settings, meaning they are here to chat or watch games but not to play themselves.',
        question3 : 'Why can\'t I watch some of my friend\'s matches ?',
        answer3 : 'At least one of the two contenders unchecked the \'Allow spectators ?\' option, making the match private.',
        question4 : 'Sometimes, I get a never-ending loading screen. Why?',
        answer4 : 'That means the server has encountered a problem and you are not connected. That means you cannot access most of the website\'s pages. Please try again later. The chat runs on the same service, so it is inaccessible as well.',
        question5 : 'I got the guy from Jurassic park telling me I didn\'t say the magic word. You think you\'re funny ?',
        answer5 : 'Yes, of course. And it happened because you tried to access an forbidden url. You think you\'re clever ?',
        question6 : 'A friend sent me that url...',
        answer6 : 'Choose better friends...'
    }
}

function French() {
    return {
        menu1 : 'Connexion',
        menu2 : 'Déconnexion',
        menu3 : 'Paramètres',
        menu4 : 'Profil',
        menu5 : 'Jouer',
        menu6 : 'Top 50',
        menu7 : 'Tournois',
        menu8 : 'A propos',
        aboutTitle : 'A propos de ce projet',
        about1 : 'Ceci est ft_transcendence, le dernier projet du tronc commun de l\'école 19.',
        about2 : 'L\'objectif est de réaliser une Single Page Application (SPA) permettant aux visiteurs de s\'affronter dans des parties de Pong !',
        about3 : 'Quelques modules ont été ajoutés à cette base :',
        module1 : 'Bootstrap et React ont servi à réaliser l\'interface',
        module2 : 'Django a servi à réaliser le back-end',
        module3 : 'Les jeux sont gérés par le serveur (API) (Sauf les parties en mode \'local\')',
        module4 : 'Le site est lié à une base de données, ce qui nous permet de tout conserver lors d\'un éventuel redémarrage (sauf le chat, qui est lié à la session courante)',
        module5 : 'Un autre jeu est disponible (échecs)',
        module6 : 'Le chat',
        module7 : 'Vous pouvez jouer en ligne, vous n\'êtes pas obligé de partager le clavier',
        module8 : 'Vous pouvez visiter le site avec (presque) n\'importe quel navigateur',
        module9 : 'Le site s\'adapte à la taille de votre écran',
        module10 : 'Vous pouvez créer un compte, gérer votre profil, ajouter d\'autres joueurs à votre liste d\'amis et bien d\'autres options sociales',
        module11 : 'Le site est disponible en anglais, français et allemand',
        about4 : 'L\'équipe est composée de :',
        question1 : 'Quelle est la différence entre un \'bloquer\' et \'rendre muet\' ?',
        answer1_1 : '\'Rendre muet\' vous empêchera de voir les messages envoyés par l\'utilisateur dans votre chat. C\'est un statut lié à la session courante. Cela signifie que si vous vous déconnectez ou si vous rechargez la page, ses messages apparaîtront de nouveau.',
        answer1_2 : '\'Bloquer\' fait également disparaître l\'utilisateur de votre chat, mais pas seulement. Il quittera votre liste d\'amis s\'il en faisait partie et ne pourra plus vous envoyer de requêtes d\'amis ni d\'invitations à jouer. Il restera également bloqué à votre prochaine connexion ou si vous rechargez la page.',
        question2 : 'Pourquoi ne puis-je parfois pas inviter un de mes amis à jouer avec moi ?',
        answer2 : 'Il est possible qu\'il ait décoché la case \'Défiable\' dans ses paramètres. Cela signifie qu\'il n\'est probablement là que pour regarder les matches d\'autres joueurs ou pour chatter.',
        question3 : 'Pourquoi ne puis-je pas assister aux matches de certains de mes amis ?',
        answer3 : 'Si au moins un des deux adversaires d\'un match a décoché la case \'Autoriser les spectateurs\' dans ses paramètres, le match est privé.',
        question4 : 'Parfois, le site reste bloqué sur l\'image d\'un escargot qui me dit qu\'un chargement est en cours. Pourquoi ?',
        answer4 : 'Cela signifie que le serveur a rencontré un problème et que vous n\'êtes pas connecté. Vous n\'avez alors pas accès à la plupart des pages du site. Veuillez réessayer plus tard. Le chat est dépendant du même service et est donc inutilisable également.',
        question5 : 'Le mec de Jurassic Park m\'a dit que je n\'avais pas dit le mot magique. Vous vous croyez drôle ?',
        answer5 : 'Oui, évidemment. Et c\'est arrivé parce que vous avez tenté d\'accéder à une url non-autorisée. Vous vous croyez malin ?',
        question6 : 'Un ami m\' envoyé cette url...',
        answer6 : 'Choisissez de meilleurs amis...'
    }
}

function Deutsch() {
    return {
        menu1 : 'Verbindung',
        menu2 : 'Trennung',
        menu3 : 'Einstellungen',
        menu4 : 'Profil',
        menu5 : 'Spielen',
        menu6 : 'Bestenliste',
        menu7 : 'Turniere',
        menu8 : 'Um',
        aboutTitle : 'Über dieses Projekt',
        about1 : 'Das ist ft_transcendence, das neueste Projekt des gemeinsamen Kerns der Schule 19.',
        about2 : 'Das Ziel besteht darin, eine Single Page Application (SPA) zu erstellen, die es Besuchern ermöglicht, an Pong-Spielen teilzunehmen!',
        about3 : 'Einige Module wurden dieser Datenbank hinzugefügt :',
        module1 : 'Zur Erstellung der Schnittstelle wurden Bootstrap und React verwendet',
        module2 : 'Django wurde verwendet, um das Backend zu erstellen',
        module3 : 'Die Spiele werden vom Server (API) verwaltet (außer Spiele im „lokalen“ Modus)',
        module4 : 'Die Seite ist mit einer Datenbank verknüpft, die es uns ermöglicht, bei einem möglichen Neustart alles beizubehalten (mit Ausnahme des Chats, der mit der aktuellen Sitzung verknüpft ist).',
        module5 : 'Ein weiteres Spiel ist verfügbar (Schach)',
        module6 : 'Der Plausch',
        module7 : 'Sie können online spielen, Sie müssen die Tastatur nicht teilen',
        module8 : 'Sie können die Seite mit (fast) jedem Browser besuchen',
        module9 : 'Die Seite passt sich der Größe Ihres Bildschirms an',
        module10 : 'Sie können ein Konto erstellen, Ihr Profil verwalten, andere Spieler zu Ihrer Freundesliste hinzufügen und viele andere soziale Optionen nutzen',
        module11 : 'Die Website ist auf Englisch, Französisch und Deutsch verfügbar',
        about4 : 'Das Team besteht aus :',
        question1 : 'Was ist der Unterschied zwischen „blockieren“ und „stumm“?',
        answer1_1 : '„Rendew mute“ verhindert, dass Sie vom Benutzer gesendete Nachrichten in Ihrem Chat sehen. Dies ist ein Status, der mit der aktuellen Sitzung verknüpft ist. Das heißt, wenn Sie sich abmelden oder die Seite neu laden, werden deren Meldungen erneut angezeigt.',
        answer1_2 : '„Blockieren“ entfernt den Benutzer auch aus Ihrem Chat, aber nicht nur das. Er verlässt Ihre Freundesliste, wenn er dort war, und kann Ihnen keine Freundschaftsanfragen oder Spieleinladungen mehr senden. Es bleibt auch beim nächsten Anmelden oder Neuladen der Seite gesperrt.',
        question2 : 'Warum kann ich manchmal einen meiner Freunde nicht einladen, mit mir zu spielen ?',
        answer2 : 'Es ist möglich, dass er in seinen Einstellungen das Kontrollkästchen „Herausfordernd“ deaktiviert hat. Das bedeutet, dass er wahrscheinlich nur da ist, um sich die Spiele anderer Spieler anzusehen oder um zu chatten.',
        question3 : 'Warum kann ich einigen Spielen meiner Freunde nicht beiwohnen ?',
        answer3 : 'Wenn mindestens einer der beiden Gegner in einem Match in seinen Einstellungen das Kontrollkästchen „Zuschauer zulassen“ deaktiviert hat, ist das Match privat.',
        question4 : 'Manchmal bleibt die Seite beim Bild einer Schnecke hängen, was mir anzeigt, dass der Ladevorgang läuft. Wofür ?',
        answer4 : 'Das bedeutet, dass beim Server ein Problem aufgetreten ist und Sie nicht verbunden sind. Dies bedeutet, dass Sie auf die meisten Seiten der Website keinen Zugriff haben. Bitte versuchen Sie es später noch einmal. Der Chat ist auf denselben Dienst angewiesen und daher ebenfalls unbrauchbar.',
        question5 : 'Der Typ aus Jurassic Park sagte mir, ich hätte das Zauberwort nicht gesagt. Findest du dich lustig?',
        answer5 : 'Ja natürlich. Und es geschah, weil Sie versucht haben, auf eine nicht autorisierte URL zuzugreifen. Glaubst du, du bist schlau?',
        question6 : 'Ein Freund hat mir diese URL geschickt...',
        answer6 : 'Wähle bessere Freunde ...'
    }
}