FROM python:3-alpine

WORKDIR /usr/src/app

COPY requirements/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install stockfish
# COPY backend .
COPY scripts/django_launch.sh .
COPY scripts/check_db.py .
