# Use an official Node runtime as a parent image
FROM node:14 as builder

# Set the working directory to /app

# Copy package.json and package-lock.json to the working directory
# COPY ./frontend/package.json .
# COPY ./frontend/package-lock.json .

# Install any needed packages specified in package.json

# Copy all files from the current directory to the working directory
COPY ../scripts/node_launch.sh /
RUN chmod +x /node_launch.sh
WORKDIR /app
COPY ./frontend .
ENTRYPOINT ["/bin/sh"]
CMD ["/node_launch.sh"]
