# # Use an official Node runtime as a parent image
# FROM node:14 as builder

# # Set the working directory to /app
# WORKDIR /app

# # Copy package.json and package-lock.json to the working directory
# COPY ./frontend/package.json .
# COPY ./frontend/package-lock.json .

# # Install any needed packages specified in package.json
# RUN npm install

# # Copy all files from the current directory to the working directory
# COPY ./frontend .

# # Build the react app into static assets
# RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache openssl

RUN mkdir -p /etc/nginx/certs

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/nginx-selfsigned.key \
    -out /etc/nginx/certs/nginx-selfsigned.crt \
    -subj "/C=EN/ST=Brussels/L=Brussels/O=19/OU=Education/CN=localhost"

# Copy config nginx
COPY ./requirements/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets from builder stage
#COPY --from=builder /app/build .

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]

