# Use an official Node runtime as a parent image
FROM node:14 as builder

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .

# Install any needed packages specified in package.json
RUN npm install

# Copy all files from the current directory to the working directory
COPY ./frontend .

# Build the React app
RUN npm run build

# Use a smaller base image for the final image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the build directory from the builder stage
COPY --from=builder /app/ /app/

# Expose port 3000 for the application
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]

