# Generated by Django 5.0.2 on 2024-06-06 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pong_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=2)),
                ('defaultGame', models.CharField(default='pong', max_length=5)),
                ('avatar', models.ImageField(blank=True, default='default_avatar.jpeg', upload_to='')),
                ('bio', models.CharField(default='', max_length=10000)),
                ('catchphrase', models.CharField(default='', max_length=10000)),
                ('status', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline')),
                ('challengeable', models.BooleanField(default=True)),
                ('spectate', models.BooleanField(default=True)),
                ('playing', models.BooleanField(default=False)),
                ('chatChannelName', models.CharField(default='', max_length=100)),
                ('matchChannelName', models.CharField(default='', max_length=100)),
                ('blocked', models.ManyToManyField(blank=True, to='profiles.profile')),
                ('chess_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_stats', to='profiles.chess_stats')),
                ('friend_requests', models.ManyToManyField(blank=True, to='profiles.profile')),
                ('friends', models.ManyToManyField(blank=True, to='profiles.profile')),
                ('pong_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_stats', to='profiles.pong_stats')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
