# Generated by Django 5.0.2 on 2024-06-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=100)),
                ('history', models.ManyToManyField(related_name='chess_history', to='game.match')),
            ],
        ),
        migrations.CreateModel(
            name='Pong_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=100)),
                ('history', models.ManyToManyField(related_name='pong_history', to='game.match')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=2)),
                ('defaultGame', models.CharField(default='pong', max_length=5)),
                ('avatar', models.ImageField(default='default_avatar.jpeg', null=True, upload_to='')),
                ('bio', models.CharField(default='', max_length=10000)),
                ('catchphrase', models.CharField(default='', max_length=10000)),
                ('status', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline')),
                ('challengeable', models.BooleanField(default=True)),
                ('spectate', models.BooleanField(default=True)),
                ('playing', models.BooleanField(default=False)),
                ('chatChannelName', models.CharField(default='', max_length=100, null=True)),
                ('matchChannelName', models.CharField(default='', max_length=100, null=True)),
                ('blocked', models.ManyToManyField(to='profiles.profile')),
                ('chess_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_stats', to='profiles.chess_stats')),
                ('friend_requests', models.ManyToManyField(to='profiles.profile')),
                ('friends', models.ManyToManyField(to='profiles.profile')),
                ('pong_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_stats', to='profiles.pong_stats')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.room')),
            ],
        ),
    ]
