# Generated by Django 5.0.2 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_player1_match_player2_room_player1_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(blank=True, related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(blank=True, related_name='chess_challengers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='chess_history', to='game.match'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='pong_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='pong_challengers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='pong_history', to='game.match'),
        ),
    ]
