# Generated by Django 5.0.2 on 2024-06-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(related_name='tournaments', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='pong_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='pong_challengers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='chess_challengers', to='profiles.profile'),
        ),
    ]
