# Generated by Django 5.0.2 on 2024-05-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matches', to='game.match'),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.room'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
