# Generated by Django 5.0.2 on 2024-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_match_game_room_cancelled_room_player1ready_and_more'),
        ('profiles', '0002_profile_matches_profile_room_profile_subscriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='chess_history', to='game.match'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='pong_history', to='game.match'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chatChannelName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='matchChannelName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
