# Generated by Django 5.0.2 on 2024-06-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_player1_match_player2_room_player1_and_more'),
        ('profiles', '0002_chess_stats_challenged_chess_stats_challengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.room'),
        ),
    ]
