# Generated by Django 5.0.2 on 2024-05-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chess_stats',
            name='challenged',
        ),
        migrations.RemoveField(
            model_name='chess_stats',
            name='challengers',
        ),
        migrations.RemoveField(
            model_name='pong_stats',
            name='challenged',
        ),
        migrations.RemoveField(
            model_name='pong_stats',
            name='challengers',
        ),
    ]
