# Generated by Django 5.0.2 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_room'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
