# Generated by Django 5.0.2 on 2024-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_chess_stats_challenged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='chess_challengers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='pong_challenged', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='pong_challengers', to='profiles.profile'),
        ),
    ]
