# Generated by Django 5.0.2 on 2024-06-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_subscriptions_profile_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_stats',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
