# Generated by Django 5.0.2 on 2024-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_room_player1_alter_room_player2_match'),
        ('profiles', '0004_chess_stats_challenged_chess_stats_challengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='match',
            new_name='room',
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(related_name='matches', to='game.match'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
    ]
