# Generated by Django 5.0.2 on 2024-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_match_profile_room_profile_matches_and_more'),
        ('tournaments', '0006_tournament_delete_specifictournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
