# Generated by Django 5.0.2 on 2024-06-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_roomtournament'),
        ('profiles', '0005_chess_stats_score_pong_stats_score'),
        ('tournaments', '0004_tournament_nextmatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(null=True, related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(null=True, related_name='chess_challengers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chess_stats',
            name='history',
            field=models.ManyToManyField(null=True, related_name='chess_history', to='game.match'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='challenged',
            field=models.ManyToManyField(null=True, related_name='pong_challenged', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='challengers',
            field=models.ManyToManyField(null=True, related_name='pong_challengers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='history',
            field=models.ManyToManyField(null=True, related_name='pong_history', to='game.match'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(null=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chatChannelName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(null=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(null=True, related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(null=True, related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
