# Generated by Django 5.0.2 on 2024-05-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_subscriptions_profile_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(related_name='requests', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='profiles.profile'),
        ),
    ]
