# Generated by Django 5.0.2 on 2024-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_roomtournament'),
        ('profiles', '0006_alter_chess_stats_challenged_and_more'),
        ('tournaments', '0004_tournament_nextmatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='chess_challengers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chess_stats',
            name='history',
            field=models.ManyToManyField(related_name='chess_history', to='game.match'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='challenged',
            field=models.ManyToManyField(related_name='pong_challenged', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='challengers',
            field=models.ManyToManyField(related_name='pong_challengers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='pong_stats',
            name='history',
            field=models.ManyToManyField(related_name='pong_history', to='game.match'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chatChannelName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subsccriptions', to='tournaments.tournament'),
        ),
    ]
