# Generated by Django 5.0.2 on 2024-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_blocked_alter_profile_friend_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
    ]
