# Generated by Django 5.0.2 on 2024-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_chess_stats_challenged_and_more'),
        ('tournaments', '0004_tournament_nextmatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
