# Generated by Django 5.0.2 on 2024-05-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_room_player1_alter_room_player2_match'),
        ('profiles', '0008_alter_profile_blocked_alter_profile_friend_requests_and_more'),
        ('tournaments', '0006_tournament_delete_specifictournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_stats',
            name='challenged',
            field=models.ManyToManyField(blank=True, related_name='chess_challenged', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chess_stats',
            name='challengers',
            field=models.ManyToManyField(blank=True, related_name='chess_challengers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matches', to='game.match'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subsccriptions', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.tournament'),
        ),
    ]
