# Generated by Django 5.0.2 on 2024-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chatChannelName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matchChannelName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
