# Generated by Django 5.0.2 on 2024-05-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
