# Generated by Django 5.0.2 on 2024-05-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chess_stats',
            old_name='loses',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='pong_stats',
            old_name='loses',
            new_name='losses',
        ),
    ]
