# Generated by Django 5.0.2 on 2024-05-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_loser_match_player2_match_player1_and_more'),
        ('profiles', '0013_profile_defaultgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.room'),
        ),
    ]
