# Generated by Django 5.0.2 on 2024-06-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_matchchannelname_profile_chatchannelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='MatchChannelName',
            new_name='mwatchChannelName',
        ),
    ]
