# Generated by Django 5.0.2 on 2024-06-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_matchchannelname_profile_mwatchchannelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mwatchChannelName',
            new_name='matchChannelName',
        ),
    ]
