# Generated by Django 5.0.2 on 2024-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_match_game_room_cancelled_room_player1replay_and_more'),
        ('profiles', '0020_rename_mwatchchannelname_profile_matchchannelname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AddField(
            model_name='chess_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='chess_history', to='game.match'),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='pong_history', to='game.match'),
        ),
    ]
