# Generated by Django 5.0.2 on 2024-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_profile_matches_chess_stats_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_stats',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pong_stats',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
